/**
 * Where Is API
 * Find out where someone is
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael_spragg@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WhereIsApi) {
      root.WhereIsApi = {};
    }
    root.WhereIsApi.Whereabouts = factory(root.WhereIsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Whereabouts model module.
   * @module model/Whereabouts
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Whereabouts</code>.
   * @alias module:model/Whereabouts
   * @class
   * @param name {String} 
   * @param _date {String} 
   * @param location {String} 
   */
  var exports = function(name, _date, location) {
    var _this = this;

    _this['name'] = name;
    _this['date'] = _date;
    _this['location'] = location;
  };

  /**
   * Constructs a <code>Whereabouts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Whereabouts} obj Optional instance to populate.
   * @return {module:model/Whereabouts} The populated <code>Whereabouts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {String} location
   */
  exports.prototype['location'] = undefined;



  return exports;
}));


