/**
 * Where Is API
 * Find out where someone is
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael_spragg@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TeamMember'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TeamMember'));
  } else {
    // Browser globals (root is window)
    if (!root.WhereIsApi) {
      root.WhereIsApi = {};
    }
    root.WhereIsApi.AdminsApi = factory(root.WhereIsApi.ApiClient, root.WhereIsApi.TeamMember);
  }
}(this, function(ApiClient, TeamMember) {
  'use strict';

  /**
   * Admins service.
   * @module api/AdminsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AdminsApi. 
   * @alias module:api/AdminsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the updateBaseLocation operation.
     * @callback module:api/AdminsApi~updateBaseLocationCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TeamMember>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updates base location
     * By passing in the appropriate parameters, you can set your location 
     * @param {String} teamMemberName pass a name in
     * @param {String} baseLocation location to be set
     * @param {module:api/AdminsApi~updateBaseLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TeamMember>}
     */
    this.updateBaseLocation = function(teamMemberName, baseLocation, callback) {
      var postBody = null;

      // verify the required parameter 'teamMemberName' is set
      if (teamMemberName == undefined || teamMemberName == null) {
        throw new Error("Missing the required parameter 'teamMemberName' when calling updateBaseLocation");
      }

      // verify the required parameter 'baseLocation' is set
      if (baseLocation == undefined || baseLocation == null) {
        throw new Error("Missing the required parameter 'baseLocation' when calling updateBaseLocation");
      }


      var pathParams = {
      };
      var queryParams = {
        'teamMemberName': teamMemberName,
        'baseLocation': baseLocation
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [TeamMember];

      return this.apiClient.callApi(
        '/location', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
